"""File organization execution engine.

TAG: ORG-001-E1
SPEC: SPEC-ORG-001

This module provides the OrganizationExecutor class that executes
file organization plans (move, copy, delete operations).

REQ-E-001: dry-run mode support
REQ-E-006~009: move/copy/delete execution
REQ-S-006: batch error isolation
REQ-U-003: transaction rollback support
"""

from __future__ import annotations

import asyncio
import json
import shutil
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING
from uuid import UUID, uuid4

from smart_file_manager.core.exceptions import ExecutionError
from smart_file_manager.organization.conflict_resolver import ConflictResolver
from smart_file_manager.organization.models import (
    BatchExecutionResult,
    ConflictStrategy,
    ExecutionResult,
    OrganizationAction,
    Progress,
)
from smart_file_manager.organization.safety_validator import SafetyValidator
from smart_file_manager.organization.transaction_manager import TransactionManager

if TYPE_CHECKING:
    from collections.abc import Awaitable, Callable


class OrganizationExecutor:
    """File organization execution engine.

    Executes organization plans generated by OrganizationPlanner.

    REQ-E-001: dry-run mode support
    REQ-E-006~009: file move/copy/delete execution
    REQ-S-006: batch error isolation
    REQ-U-003: transaction rollback support

    Attributes:
        DEFAULT_TRASH_DIR: Default path for trash directory.
    """

    DEFAULT_TRASH_DIR = Path.home() / ".smart_file_manager" / "trash"

    def __init__(
        self,
        safety_validator: SafetyValidator | None = None,
        transaction_manager: TransactionManager | None = None,
        conflict_resolver: ConflictResolver | None = None,
        trash_dir: Path | None = None,
        progress_callback: Callable[[Progress], Awaitable[None]] | None = None,
    ) -> None:
        """Initialize OrganizationExecutor.

        Args:
            safety_validator: Safety validator instance (creates default if None).
            transaction_manager: Transaction manager instance (creates default if None).
            conflict_resolver: Conflict resolver instance (creates default if None).
            trash_dir: Path to trash directory.
            progress_callback: Async callback for progress updates.
        """
        self._safety_validator = safety_validator or SafetyValidator()
        self._transaction_manager = transaction_manager or TransactionManager()
        self._conflict_resolver = conflict_resolver or ConflictResolver()
        self._trash_dir = trash_dir or self.DEFAULT_TRASH_DIR
        self._progress_callback = progress_callback

        # Track in-progress files to prevent concurrent operations
        self._in_progress: set[Path] = set()
        self._in_progress_lock = asyncio.Lock()

    async def execute(
        self,
        action: OrganizationAction,
        *,
        dry_run: bool = False,
        conflict_strategy: ConflictStrategy = ConflictStrategy.SKIP,
    ) -> ExecutionResult:
        """Execute a single file organization action.

        Args:
            action: The organization action to execute.
            dry_run: If True, simulate without actual file changes (REQ-E-001).
            conflict_strategy: Strategy for handling file conflicts.

        Returns:
            ExecutionResult with operation status and details.
        """
        start_time = datetime.now()
        target_path = action.target_path or Path("")

        # 1. Safety validation
        validation = self._safety_validator.validate_plan(
            source_path=action.source_path,
            target_path=target_path,
            action=action.action,
        )

        if not validation.valid:
            return self._create_result(
                success=False,
                action=action,
                target_path=target_path,
                error="; ".join(validation.errors),
                start_time=start_time,
            )

        # 2. Dry-run mode (REQ-E-001)
        if dry_run:
            # Only detect conflicts, don't perform actual operations
            await self._conflict_resolver.detect_conflicts_for_action(action)
            return self._create_result(
                success=True,
                action=action,
                target_path=target_path,
                start_time=start_time,
            )

        # 3. Check for concurrent operations on same file
        async with self._in_progress_lock:
            if action.source_path in self._in_progress:
                return self._create_result(
                    success=False,
                    action=action,
                    target_path=target_path,
                    error="File is already being processed",
                    start_time=start_time,
                )
            self._in_progress.add(action.source_path)

        transaction_id: str | None = None
        try:
            # 4. Begin transaction
            transaction_id = await self._transaction_manager.begin()

            # 5. Handle conflicts
            final_target = target_path
            conflict = await self._conflict_resolver.detect_conflicts_for_action(action)
            if conflict:
                final_target, should_proceed = await self._conflict_resolver.resolve(
                    conflict, conflict_strategy
                )
                if not should_proceed:
                    await self._transaction_manager.commit(transaction_id)
                    return self._create_result(
                        success=False,
                        action=action,
                        target_path=target_path,
                        error="Operation skipped due to conflict",
                        start_time=start_time,
                    )

            # 6. Execute the actual file operation
            actual_target = await self._execute_action(action, final_target, transaction_id)

            # 7. Commit transaction
            await self._transaction_manager.commit(transaction_id)

            return self._create_result(
                success=True,
                action=action,
                target_path=actual_target,
                transaction_id=uuid4(),  # Use UUID for result
                start_time=start_time,
            )

        except Exception as e:
            # Rollback on error
            if transaction_id:
                await self._transaction_manager.rollback(transaction_id)

            return self._create_result(
                success=False,
                action=action,
                target_path=target_path,
                error=str(e),
                start_time=start_time,
            )

        finally:
            async with self._in_progress_lock:
                self._in_progress.discard(action.source_path)

    async def execute_batch(
        self,
        actions: list[OrganizationAction],
        *,
        dry_run: bool = False,
        conflict_strategy: ConflictStrategy = ConflictStrategy.SKIP,
        rollback_on_error: bool = False,
        concurrency: int = 5,
    ) -> BatchExecutionResult:
        """Execute a batch of file organization actions.

        Args:
            actions: List of actions to execute.
            dry_run: If True, simulate without actual file changes.
            conflict_strategy: Strategy for handling file conflicts.
            rollback_on_error: If True, rollback all on any failure.
            concurrency: Maximum concurrent operations.

        Returns:
            BatchExecutionResult with batch operation status.

        REQ-S-006: Individual errors don't stop batch processing.
        """
        start_time = datetime.now()
        semaphore = asyncio.Semaphore(concurrency)
        batch_transaction_ids: list[str] = []

        async def execute_with_semaphore(action: OrganizationAction, index: int) -> ExecutionResult:
            async with semaphore:
                result = await self.execute(
                    action,
                    dry_run=dry_run,
                    conflict_strategy=conflict_strategy,
                )

                # Progress callback
                if self._progress_callback:
                    elapsed = (datetime.now() - start_time).total_seconds()
                    progress = Progress(
                        current=index + 1,
                        total=len(actions),
                        percentage=(index + 1) / len(actions) * 100,
                        current_file=str(action.source_path),
                        eta_seconds=None,
                        elapsed_seconds=elapsed,
                    )
                    await self._progress_callback(progress)

                return result

        # Execute all actions concurrently
        tasks = [execute_with_semaphore(action, i) for i, action in enumerate(actions)]
        results = await asyncio.gather(*tasks, return_exceptions=True)

        # Process results
        processed_results: list[ExecutionResult] = []
        for i, result in enumerate(results):
            if isinstance(result, Exception):
                processed_results.append(
                    self._create_result(
                        success=False,
                        action=actions[i],
                        target_path=actions[i].target_path or Path(""),
                        error=str(result),
                        start_time=start_time,
                    )
                )
            else:
                processed_results.append(result)
                if result.transaction_id:
                    batch_transaction_ids.append(str(result.transaction_id))

        # Count results
        successful = sum(1 for r in processed_results if r.success)
        failed = len(processed_results) - successful

        # Handle rollback_on_error
        if rollback_on_error and failed > 0 and not dry_run:
            for tid in batch_transaction_ids:
                try:
                    await self._transaction_manager.rollback(tid)
                except Exception:
                    pass  # Best effort rollback
            successful = 0
            failed = len(processed_results)

        return BatchExecutionResult(
            successful=successful,
            failed=failed,
            total=len(actions),
            results=processed_results,
            transaction_id=uuid4(),
        )

    async def _execute_action(
        self,
        action: OrganizationAction,
        target_path: Path,
        transaction_id: str,
    ) -> Path:
        """Execute the actual file operation.

        Args:
            action: The action to execute.
            target_path: Final target path (after conflict resolution).
            transaction_id: Current transaction ID.

        Returns:
            Actual path where file was saved.

        Raises:
            ExecutionError: If action type is not supported.
        """
        source = action.source_path

        # Create target directory if needed (REQ-E-008)
        if target_path and target_path.parent:
            target_path.parent.mkdir(parents=True, exist_ok=True)

        if action.action == "move":
            # Move operation (REQ-E-006)
            await self._transaction_manager.record(
                transaction_id=transaction_id,
                action="move",
                source_path=source,
                target_path=target_path,
            )
            shutil.move(str(source), str(target_path))
            return target_path

        elif action.action == "copy":
            # Copy operation (REQ-E-007)
            await self._transaction_manager.record(
                transaction_id=transaction_id,
                action="copy",
                source_path=source,
                target_path=target_path,
            )
            shutil.copy2(str(source), str(target_path))
            return target_path

        elif action.action == "delete":
            # Delete to trash (REQ-E-009, REQ-E-010)
            trash_path = await self._move_to_trash(source, transaction_id)
            return trash_path

        else:
            raise ExecutionError(
                f"Unsupported action type: {action.action}",
                operation=action.action,
                file_path=str(source),
            )

    async def _move_to_trash(
        self,
        source: Path,
        transaction_id: str,
    ) -> Path:
        """Move file to trash with metadata.

        REQ-E-009: Move to trash instead of permanent delete.
        REQ-E-010: Store metadata (original path, deletion time).

        Args:
            source: Source file path.
            transaction_id: Current transaction ID.

        Returns:
            Path where file was moved in trash.
        """
        # Create date-based trash directory
        date_str = datetime.now().strftime("%Y-%m-%d")
        trash_date_dir = self._trash_dir / date_str
        trash_date_dir.mkdir(parents=True, exist_ok=True)

        # Generate unique filename with timestamp
        timestamp = datetime.now().strftime("%H%M%S_%f")
        trash_filename = f"{timestamp}_{source.name}"
        trash_path = trash_date_dir / trash_filename

        # Create metadata (REQ-E-010)
        metadata = {
            "original_path": str(source),
            "deleted_at": datetime.now().isoformat(),
            "auto_delete_after": datetime.now().timestamp() + 30 * 24 * 60 * 60,  # 30 days
            "transaction_id": transaction_id,
        }
        metadata_path = trash_path.with_suffix(trash_path.suffix + ".meta.json")

        # Record in transaction
        await self._transaction_manager.record(
            transaction_id=transaction_id,
            action="delete",
            source_path=source,
            target_path=trash_path,
            metadata=metadata,
        )

        # Move file to trash
        shutil.move(str(source), str(trash_path))

        # Write metadata file
        with open(metadata_path, "w", encoding="utf-8") as f:
            json.dump(metadata, f, ensure_ascii=False, indent=2)

        return trash_path

    def _create_result(
        self,
        *,
        success: bool,
        action: OrganizationAction,
        target_path: Path,
        error: str | None = None,
        transaction_id: UUID | None = None,
        start_time: datetime,
    ) -> ExecutionResult:
        """Create an ExecutionResult.

        Args:
            success: Whether operation succeeded.
            action: The executed action.
            target_path: Target path.
            error: Error message if failed.
            transaction_id: Transaction ID if successful.
            start_time: When operation started.

        Returns:
            ExecutionResult instance.
        """
        processing_time = (datetime.now() - start_time).total_seconds() * 1000
        return ExecutionResult(
            success=success,
            file_path=action.source_path,
            target_path=target_path,
            action=action.action,
            processing_time_ms=processing_time,
            error=error,
            transaction_id=transaction_id or uuid4(),
        )

    @property
    def trash_dir(self) -> Path:
        """Get trash directory path."""
        return self._trash_dir


__all__ = ["OrganizationExecutor"]
