"""File organization service Facade.

TAG: ORG-001-F1
SPEC: SPEC-ORG-001

This module provides the OrganizationService class that integrates all
organization components into a unified facade interface.

Requirements Coverage:
    REQ-U-001: Safety validation (via SafetyValidator)
    REQ-S-001: dry-run mode support
    REQ-E-001~011: File operation execution
    REQ-S-003: Conflict resolution strategies
    REQ-U-003: Rollback functionality
    REQ-E-003, REQ-S-006: Batch processing
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from smart_file_manager.organization.conflict_resolver import ConflictResolver
from smart_file_manager.organization.models import (
    BatchExecutionResult,
    ConflictStrategy,
    ExecutionResult,
    OrganizationAction,
    Progress,
    RollbackResult,
    ValidationResult,
)
from smart_file_manager.organization.organization_executor import OrganizationExecutor
from smart_file_manager.organization.progress_tracker import ProgressTracker
from smart_file_manager.organization.safety_validator import SafetyValidator
from smart_file_manager.organization.transaction_manager import TransactionManager

if TYPE_CHECKING:
    from collections.abc import Awaitable, Callable
    from typing import Any


class OrganizationService:
    """File organization service Facade.

    SPEC-CLASS-001's OrganizationPlanner generates plans that this service
    executes through a unified interface.

    Facade Pattern: Provides a simple interface to complex subsystems.

    This class integrates:
        - SafetyValidator: Validates operations before execution
        - TransactionManager: Manages transaction logging and rollback
        - ConflictResolver: Resolves file conflicts
        - OrganizationExecutor: Executes file operations
        - ProgressTracker: Tracks batch operation progress

    Attributes:
        DEFAULT_TRASH_DIR: Default path for trash directory.

    Example:
        service = OrganizationService(trash_dir=Path("/tmp/trash"))
        action = OrganizationAction(
            action="move",
            source_path=Path("/source/file.txt"),
            target_path=Path("/target/file.txt"),
            options={},
        )
        result = await service.execute_plan(action)
    """

    DEFAULT_TRASH_DIR = Path.home() / ".smart_file_manager" / "trash"
    DEFAULT_TRANSACTION_DIR = Path.home() / ".smart_file_manager" / "transactions"

    def __init__(
        self,
        trash_dir: Path | None = None,
        transaction_dir: Path | None = None,
        default_conflict_strategy: ConflictStrategy = ConflictStrategy.SKIP,
        user_prompt_callback: Callable[..., Awaitable[ConflictStrategy]] | None = None,
    ) -> None:
        """Initialize OrganizationService.

        Args:
            trash_dir: Path to trash directory. Uses DEFAULT_TRASH_DIR if None.
            transaction_dir: Path to transaction log directory.
                Uses DEFAULT_TRANSACTION_DIR if None.
            default_conflict_strategy: Default strategy for handling conflicts.
            user_prompt_callback: Async callback for ASK_USER conflict strategy.
                Called with conflict details, should return a ConflictStrategy.
        """
        self._trash_dir = trash_dir or self.DEFAULT_TRASH_DIR
        self._transaction_dir = transaction_dir or self.DEFAULT_TRANSACTION_DIR
        self._default_conflict_strategy = default_conflict_strategy

        # Initialize subsystem components
        self._safety_validator = SafetyValidator()
        self._transaction_manager = TransactionManager(
            transaction_dir=self._transaction_dir,
        )
        self._conflict_resolver = ConflictResolver(
            default_strategy=default_conflict_strategy,
            user_prompt_callback=user_prompt_callback,
        )
        self._executor = OrganizationExecutor(
            safety_validator=self._safety_validator,
            transaction_manager=self._transaction_manager,
            conflict_resolver=self._conflict_resolver,
            trash_dir=self._trash_dir,
        )

    async def execute_plan(
        self,
        action: OrganizationAction,
        *,
        dry_run: bool = False,
        conflict_strategy: ConflictStrategy | None = None,
    ) -> ExecutionResult:
        """Execute a single file organization plan.

        Executes a single action generated by OrganizationPlanner.

        Args:
            action: The organization action to execute.
            dry_run: If True, simulate without actual file changes (REQ-S-001).
            conflict_strategy: Strategy for handling conflicts.
                Uses default_conflict_strategy if None.

        Returns:
            ExecutionResult with operation status and details.

        Example:
            action = OrganizationAction(
                action="move",
                source_path=Path("/source.txt"),
                target_path=Path("/target.txt"),
                options={},
            )
            result = await service.execute_plan(action, dry_run=True)
        """
        strategy = conflict_strategy or self._default_conflict_strategy
        return await self._executor.execute(
            action,
            dry_run=dry_run,
            conflict_strategy=strategy,
        )

    async def execute_batch(
        self,
        actions: list[OrganizationAction],
        *,
        dry_run: bool = False,
        conflict_strategy: ConflictStrategy | None = None,
        rollback_on_error: bool = False,
        concurrency: int = 5,
        progress_callback: Callable[[Progress], Awaitable[None]] | None = None,
    ) -> BatchExecutionResult:
        """Execute a batch of file organization plans.

        Executes multiple actions generated by OrganizationPlanner.
        Supports concurrent execution with configurable limits.

        Args:
            actions: List of organization actions to execute.
            dry_run: If True, simulate without actual file changes.
            conflict_strategy: Strategy for handling conflicts.
                Uses default_conflict_strategy if None.
            rollback_on_error: If True, rollback all operations on any failure.
            concurrency: Maximum number of concurrent operations.
            progress_callback: Async callback for progress updates.
                Called with Progress object on each update.

        Returns:
            BatchExecutionResult with batch operation status.

        REQ-E-003, REQ-S-006: Batch processing with error isolation.
        """
        strategy = conflict_strategy or self._default_conflict_strategy

        # Set up ProgressTracker if callback provided
        tracker: ProgressTracker | None = None
        if progress_callback:
            tracker = ProgressTracker(
                total=len(actions),
                callback=progress_callback,
            )

            # Create executor progress callback
            async def executor_progress_callback(progress: Progress) -> None:
                if tracker:
                    await tracker.update(
                        current=progress.current,
                        current_file=progress.current_file,
                    )

            # Store original callback and replace
            original_callback = self._executor._progress_callback
            self._executor._progress_callback = executor_progress_callback
        else:
            original_callback = None

        try:
            if tracker:
                await tracker.start()

            result = await self._executor.execute_batch(
                actions,
                dry_run=dry_run,
                conflict_strategy=strategy,
                rollback_on_error=rollback_on_error,
                concurrency=concurrency,
            )

            if tracker:
                await tracker.complete()

            return result

        finally:
            # Restore original callback
            if progress_callback:
                self._executor._progress_callback = original_callback

    async def validate(
        self,
        action: OrganizationAction,
    ) -> ValidationResult:
        """Validate an action without executing (no dry-run).

        Performs safety validation on the action.

        Args:
            action: The organization action to validate.

        Returns:
            ValidationResult with validation status and any issues.

        REQ-U-001: Safety validation.

        Raises:
            ProtectedPathError: If source or target is a protected path.
            InsufficientSpaceError: If not enough disk space.
        """
        target_path = action.target_path or Path("")
        return self._safety_validator.validate_plan(
            source_path=action.source_path,
            target_path=target_path,
            action=action.action,
        )

    async def rollback(
        self,
        transaction_id: str,
    ) -> RollbackResult:
        """Rollback a transaction.

        Reverses all operations in the specified transaction.

        Args:
            transaction_id: ID of the transaction to rollback.

        Returns:
            RollbackResult with rollback status and details.

        REQ-U-003: Rollback functionality.

        Raises:
            TransactionError: If transaction not found.
        """
        return await self._transaction_manager.rollback(transaction_id)

    async def get_transaction_history(
        self,
        limit: int = 100,
    ) -> list[dict[str, Any]]:
        """Get recent transaction history.

        Args:
            limit: Maximum number of transactions to return.

        Returns:
            List of transaction summaries ordered by newest first.
            Each dict contains: transaction_id, entries_count, completed_at.
        """
        return await self._transaction_manager.get_transaction_history(limit)

    async def recover_from_crash(self) -> list[str]:
        """Recover from crash - detect incomplete transactions.

        Scans transaction directory for incomplete transactions
        that may need recovery or rollback.

        Returns:
            List of incomplete transaction IDs.
        """
        return await self._transaction_manager.recover_from_crash()

    @property
    def trash_dir(self) -> Path:
        """Get trash directory path.

        Returns:
            Path to the trash directory.
        """
        return self._executor.trash_dir

    @property
    def default_conflict_strategy(self) -> ConflictStrategy:
        """Get the default conflict resolution strategy.

        Returns:
            Current default ConflictStrategy.
        """
        return self._default_conflict_strategy

    @default_conflict_strategy.setter
    def default_conflict_strategy(self, value: ConflictStrategy) -> None:
        """Set the default conflict resolution strategy.

        Updates both the service's default and the conflict resolver's default.

        Args:
            value: New default ConflictStrategy.
        """
        self._default_conflict_strategy = value
        self._conflict_resolver.default_strategy = value


__all__ = ["OrganizationService"]
