global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'smart-file-manager'
    static_configs:
      - targets: ['smart-file-manager-v4:8001']
        labels:
          service: 'api'
      - targets: ['smart-file-manager-v4:9001']
        labels:
          service: 'supervisor'
          
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
        labels:
          service: 'vector-db'
          
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
        labels:
          service: 'cache'
